### ISSUE TITLE
Password field shouldn't show password input text

### ISSUE THREAD

**Issue by josephdburdick** [lennym/prompt-wizard#1]

**Comment by lennym** [comment]
Thanks for opening an issue @josephdburdick 

I haven't looked at this code in a while, but I can't reproduce this issue running [the password example in the repo](https://github.com/lennym/prompt-wizard/blob/master/examples/password.js) - the password shows as asterisks when entered.

Are you able to provide a minimal test case, and ideally details of the node version and OS you're running on?

**Comment by josephdburdick** [comment]
Interesting, I just tried again and I no longer experience this issue. I am running OSX 10.13, Node v8.1.4. I'm closing this, thank you for replying!
